# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details.

{
    'name': 'Courier Management System',
    'version': '10.0.1.0.1',
    'category': 'Extra Tools',
    'description': 'This Module manages activities and operations of a courier company',
    'author': 'Febno',
    'depends': ['base',
        'hr',
        'sale',
        'delivery',
        'account_cancel',
        'courier_website',
        'base_geolocalize',
    ],
    'data': [
        'data/email_template_view.xml',
        'data/scan_seq_view.xml',
        'wizard/courier_assign_wizard.xml',
        # 'security/courier_record_rule_view.xml',
        'security/ir.model.access.csv',
        'views/account_invoice_view.xml',
        'views/courier_view.xml',
        'views/res_company_view.xml',
        "views/area_area_view.xml",
        "views/city_city_view.xml",
        "views/zone_zone_view.xml",
        'views/driver_commission_views.xml',
        'views/hr_employee_views.xml',
        'views/partner_views.xml',
        'views/booking_website_templates.xml',
        'views/transaction_website.xml',
        # 'views/courier_warehouse_list_view.xml',
        # 'views/transaction_website.xml',
        # 'views/delivery_methods_view.xml',
        'data/sequence_data_view.xml',
        'data/data_view.xml',
        'report/report_courier_template_view.xml',
        'report/courier_challan_template_view.xml',
        'report/report_register.xml',
        'report/courier_report.xml',
        'report/report_account_statement.xml',
        'report/invoice_report.xml',
        'wizard/sender_account_statement_views.xml',
        'wizard/courier_bulk_import.xml',
        'wizard/inscan_wizard.xml',
        'wizard/outscan_wizard.xml',
        'wizard/empost_print.xml',
        'wizard/manual_number.xml',
        'wizard/export_report.xml',
        'data/customer_sequence_view.xml',
        'views/website_bulk_import.xml',
        'report/report.xml',
        'report/courier_run.xml',
        'report/empost_report.xml',
        'report/export_xlsx.xml',

        # 'views/courier_data.xml',
        # 'views/courier_demo_data.xml'
    ],
    'images': ['static/description/courier_banner.png'],
    'installable': True,
}
